### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by komodo472** [dicej/componentize-py#12]
When running componentize-py 0.4.0 on Windows for the [demo](https://github.com/dicej/component-sandbox-demo) I get the following error:

```
AssertionError: Access is denied. (os error 5)
```

Any ideas on where this error is coming from? It's extremely vague and I'm not sure how to determine which part of the code is generating this error

**Comment by dicej** [comment]
Thanks for reporting this, @komodo472.  I'll admit I don't test on Windows frequently, so stuff like this sometimes slips through.  I should update CI to test each PR on Windows and Mac -- not just Linux.

Anyway, I'll investigate this as soon as I have a chance (hopefully today or tomorrow).

**Comment by dicej** [comment]
@komodo472 This is fixed in `componentize-py` 0.4.2.  You can upgrade using `pip install --upgrade componentize-py`.  Please also pull the latest from the `component-sandbox-demo` repo, since I had to make some changes to make it compatible with 0.4.2.

**Comment by komodo472** [comment]
It works! Thank you!
